# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "home"
name = "Home"
url = "https://chuankepang.github.io/"
weight = -100

[social.params]
icon = "home"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:chuankepang@buaa.edu.cn"
weight = -90

[social.params]
icon = "mail"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/chuankepang"
weight = -80

[social.params]
icon = "brand-github"

[[social]]
identifier = "blog"
name = "Blog"
url = "https://isneal.github.io/"
weight = -70

[social.params]
icon = "book"

[[social]]
identifier = "wechat"
name = "Wechat"
url = "https://chuankepang.github.io/image/Wechat/Wechat.png"
weight = 0

[social.params]
icon = "brand-wechat"

#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com"

#[social.params]
#icon = "brand-twitter"
